import {neon} from '@neondatabase/serverless';
import {verifyToken} from '@clerk/backend';
import Stripe from 'stripe';
import {z} from 'zod';
import {createHash,randomUUID} from 'node:crypto';
import {get} from '@vercel/blob';
import {Readable} from 'node:stream';
import {pipeline} from 'node:stream/promises';
export class ServiceError extends Error{constructor(status,message){super(message);this.status=status;}}
export function config(){const origin=process.env.UNDERWRITER_PUBLIC_ORIGIN;if(process.env.UNDERWRITER_SERVICE_ENABLED!=='true'||!process.env.UNDERWRITER_DATABASE_URL||!origin||new URL(origin).origin!==origin||!origin.startsWith('https://'))throw new ServiceError(503,'Configuration service is not available. The free MIT toolkit remains available.');return {db:neon(process.env.UNDERWRITER_DATABASE_URL),origin};}
export function stripe(){if(!process.env.UNDERWRITER_STRIPE_SECRET_KEY)throw new ServiceError(503,'Quote payment is not configured');return new Stripe(process.env.UNDERWRITER_STRIPE_SECRET_KEY,{timeout:10000,maxNetworkRetries:0});}
const operators=()=>new Set((process.env.UNDERWRITER_OPERATOR_CLERK_IDS||'').split(',').map(s=>s.trim()).filter(Boolean));
async function user(req){const token=req.headers.authorization?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new ServiceError(401,'Sign in to continue');try{const claims=await verifyToken(token,{secretKey:process.env.CLERK_SECRET_KEY,authorizedParties:[config().origin]});return claims.sub;}catch{throw new ServiceError(401,'Sign in again to continue');}}
const validId=s=>z.string().uuid().parse(s);
const hash=s=>createHash('sha256').update(s).digest('hex');
function present(r,operator=false){return {id:r.id,request:r.request,stage:r.stage,quote:r.quote,quoteRevision:r.quote_revision,acceptedRevision:r.accepted_revision,paymentStatus:r.payment_status,packageReady:!!r.package_path,deliveryNote:r.delivery_note,deliveredAt:r.delivered_at,customerAcceptedAt:r.customer_accepted_at,createdAt:r.created_at,...(operator?{operatorNote:r.operator_note}:{})};}
async function row(id,who,operator=false){const {db}=config();const rows=await db`SELECT * FROM uw_engagements WHERE id=${validId(id)}::uuid AND (buyer=${who} OR ${operator})`;if(!rows[0])throw new ServiceError(404,'Engagement not found');return rows[0];}
async function lease(id,run){const {db}=config(),token=randomUUID();const rows=await db`UPDATE uw_engagements SET lease=${token}::uuid,lease_until=now()+interval '90 seconds' WHERE id=${validId(id)}::uuid AND (lease_until IS NULL OR lease_until<now()) RETURNING *`;if(!rows[0])throw new ServiceError(409,'Engagement is being processed. Retry shortly.');try{return await run(rows[0]);}finally{await db`UPDATE uw_engagements SET lease=NULL,lease_until=NULL WHERE id=${id}::uuid AND lease=${token}::uuid`;}}
async function event(id,actor,action,detail={}){await config().db`INSERT INTO uw_service_events(engagement_id,actor,action,detail) VALUES(${id}::uuid,${actor},${action},${JSON.stringify(detail)}::jsonb)`;}
export async function reconcile(id){return lease(id,async r=>{if(!r.checkout_id)return r;const client=stripe(),s=await client.checkout.sessions.retrieve(r.checkout_id,{expand:['payment_intent.latest_charge']});const pi=typeof s.payment_intent==='object'?s.payment_intent:null,charge=typeof pi?.latest_charge==='object'?pi.latest_charge:null;const q=r.quote;
 if(s.client_reference_id!==r.id||s.metadata?.engagement!==r.id||s.metadata?.revision!==String(r.accepted_revision)||s.amount_total!==q.amountCents||s.currency!==q.currency)throw new ServiceError(409,'Payment does not match the accepted quote');
 let status=s.payment_status==='paid'&&pi?.status==='succeeded'&&charge?.paid?'paid':s.status==='expired'?'expired':'pending';if(charge?.disputed)status='disputed';if(charge?.refunded||charge?.amount_refunded>0)status='refunded';
 const {db}=config();return (await db`UPDATE uw_engagements SET payment_status=${status},payment_intent=${pi?.id||null},updated_at=now() WHERE id=${id}::uuid RETURNING *`)[0];});}
async function checkout(who,id,input){const accepted=z.object({revision:z.number().int().positive(),acceptScope:z.literal(true)}).strict().parse(input);await row(id,who);return lease(id,async r=>{const {db,origin}=config();if(r.checkout_id){const session=await stripe().checkout.sessions.retrieve(r.checkout_id);if(session.status==='open'&&session.url)return {url:session.url};throw new ServiceError(409,'This quote already has a payment session. Refresh payment status; an operator must review expired or changed engagements.');}
 if(!r.quote||r.quote_revision!==accepted.revision||Date.parse(r.quote.expiresAt)<Date.now())throw new ServiceError(409,'This quote changed or expired. Request an updated quote');
 if(r.accepted_at&&Date.now()-Date.parse(r.accepted_at)>23*3600000)throw new ServiceError(409,'Payment recovery requires operator review');
 const q=r.quote;await db`UPDATE uw_engagements SET accepted_revision=${accepted.revision},accepted_at=COALESCE(accepted_at,now()),payment_status='pending' WHERE id=${id}::uuid`;
 const s=await stripe().checkout.sessions.create({mode:'payment',client_reference_id:id,metadata:{engagement:id,revision:String(accepted.revision)},payment_intent_data:{metadata:{engagement:id}},line_items:[{quantity:1,price_data:{currency:q.currency,unit_amount:q.amountCents,product_data:{name:'Underwriter OS configuration engagement',description:`Accepted scope revision ${accepted.revision}`}}}],success_url:`${origin}/configuration.html`,cancel_url:`${origin}/configuration.html`},{idempotencyKey:`uw-quote-${id}-${accepted.revision}`});
 await db`UPDATE uw_engagements SET checkout_id=${s.id} WHERE id=${id}::uuid`;await event(id,who,'quote_accepted',{revision:accepted.revision});return {url:s.url};});}
async function raw(req){let bytes=0;const chunks=[];for await(const c of req){const b=Buffer.isBuffer(c)?c:Buffer.from(c);bytes+=b.length;if(bytes>64000)throw new ServiceError(413,'Request too large');chunks.push(b);}return Buffer.concat(chunks);}
export default async function handler(req,res){res.setHeader('Cache-Control','private, no-store');try{const {db,origin}=config();const url=new URL(req.url,origin),action=String(req.query?.action||url.pathname.split('/').pop()),id=url.searchParams.get('id');
 if(action==='config'&&req.method==='GET'){res.json({publishableKey:process.env.CLERK_PUBLISHABLE_KEY||''});return;}
 const bytes=['POST','PATCH'].includes(req.method)?await raw(req):Buffer.alloc(0);
 if(action==='webhook'&&req.method==='POST'){if(!process.env.UNDERWRITER_STRIPE_WEBHOOK_SECRET)throw new ServiceError(503,'Webhook unavailable');let e;try{e=stripe().webhooks.constructEvent(bytes,req.headers['stripe-signature'],process.env.UNDERWRITER_STRIPE_WEBHOOK_SECRET);}catch{throw new ServiceError(400,'Invalid webhook signature');}const o=e.data.object;let found;if(e.type.startsWith('checkout.session.'))found=(await db`SELECT id FROM uw_engagements WHERE checkout_id=${o.id}`)[0];else{let pi=o.payment_intent;if(e.type.startsWith('charge.dispute.')&&o.charge){const charge=await stripe().charges.retrieve(typeof o.charge==='string'?o.charge:o.charge.id);pi=charge.payment_intent;}if(pi)found=(await db`SELECT id FROM uw_engagements WHERE payment_intent=${typeof pi==='string'?pi:pi.id}`)[0];}if(found){await reconcile(found.id);await db`INSERT INTO uw_stripe_events(id,engagement_id) VALUES(${e.id},${found.id}::uuid) ON CONFLICT DO NOTHING`;}res.json({received:true});return;}
 const who=await user(req),operator=operators().has(who);let input={};if(bytes.length){try{input=JSON.parse(bytes.toString());}catch{throw new ServiceError(400,'Invalid JSON');}}
 if(action==='list'&&req.method==='GET'){const offset=z.coerce.number().int().min(0).max(100000).parse(url.searchParams.get('offset')||0);const op=url.searchParams.get('operator')==='true';if(op&&!operator)throw new ServiceError(403,'Operator access required');const rows=await db`SELECT * FROM uw_engagements WHERE buyer=${who} OR ${op&&operator} ORDER BY created_at DESC LIMIT 50 OFFSET ${offset}`;res.json({operator,engagements:rows.map(r=>present(r,op&&operator)),offset,limit:50});return;}
 if(action==='inquiry'&&req.method==='POST'){const p=z.object({id:z.string().uuid(),firm:z.string().trim().min(1).max(160),contactEmail:z.email().max(254),runtime:z.enum(['Claude Desktop','Codex','Other']),runtimeDetails:z.string().trim().max(1000),scope:z.string().trim().min(20).max(12000),acceptanceCriteria:z.string().trim().min(20).max(6000),constraints:z.string().trim().max(4000),consent:z.literal(true)}).strict().parse(input);const {id:requestId,...request}=p,serialized=JSON.stringify(request);const existing=(await db`SELECT * FROM uw_engagements WHERE id=${requestId}::uuid`)[0];if(existing){if(existing.buyer!==who||existing.request_hash!==hash(serialized))throw new ServiceError(409,'Request identifier already used');res.json(present(existing));return;}const n=(await db`SELECT count(*)::int AS n FROM uw_engagements WHERE buyer=${who} AND created_at>now()-interval '1 day'`)[0].n;if(n>=5)throw new ServiceError(429,'Daily inquiry limit reached');const created=(await db`INSERT INTO uw_engagements(id,buyer,request,request_hash) VALUES(${requestId}::uuid,${who},${serialized}::jsonb,${hash(serialized)}) RETURNING *`)[0];res.status(201).json(present(created));return;}
 if(action==='quote'&&req.method==='POST'){if(!operator)throw new ServiceError(403,'Operator access required');const p=z.object({revision:z.number().int().min(0),amountCents:z.number().int().min(1).max(100000000),currency:z.literal('usd'),scope:z.string().trim().min(20).max(12000),acceptanceCriteria:z.string().trim().min(20).max(6000),terms:z.string().trim().min(20).max(12000),expiresAt:z.iso.datetime()}).strict().parse(input);if(Date.parse(p.expiresAt)<=Date.now()||Date.parse(p.expiresAt)>Date.now()+90*86400000)throw new ServiceError(400,'Quote expiry must be within 90 days');await row(id,who,true);const output=await lease(id,async r=>{if(r.accepted_at||r.checkout_id||r.quote_revision!==p.revision)throw new ServiceError(409,'Accepted or changed quote cannot be overwritten');const {revision,...quote}=p;const saved=(await db`UPDATE uw_engagements SET quote=${JSON.stringify(quote)}::jsonb,quote_revision=quote_revision+1,stage='quoted',updated_at=now() WHERE id=${id}::uuid RETURNING *`)[0];await event(id,who,'quote_published',{revision:saved.quote_revision,quote});return saved;});res.json(present(output,true));return;}
 if(action==='note'&&req.method==='POST'){if(!operator)throw new ServiceError(403,'Operator access required');const p=z.object({note:z.string().trim().max(10000),stage:z.enum(['new','reviewing','configuring'])}).strict().parse(input);const r=await row(id,who,true);if(p.stage==='configuring'&&(await reconcile(id)).payment_status!=='paid')throw new ServiceError(409,'Payment must be verified before configuration');if(r.delivered_at)throw new ServiceError(409,'Delivered engagement stage is fixed');await db`UPDATE uw_engagements SET operator_note=${p.note},stage=${p.stage},updated_at=now() WHERE id=${id}::uuid`;await event(id,who,'operator_update',p);res.json({saved:true});return;}
 if(action==='checkout'&&req.method==='POST'){res.json(await checkout(who,id,input));return;}
 if(action==='refresh'&&req.method==='POST'){await row(id,who,operator);res.json(present(await reconcile(id),operator));return;}
 if(action==='accept-delivery'&&req.method==='POST'){const r=await row(id,who);if(!r.delivered_at||!r.package_path)throw new ServiceError(409,'No delivered package is available');if(input.acceptDelivery!==true)throw new ServiceError(400,'Explicit delivery acceptance required');await db`UPDATE uw_engagements SET customer_accepted_at=COALESCE(customer_accepted_at,now()),stage='accepted' WHERE id=${id}::uuid`;res.json({accepted:true});return;}
 if(action==='download'&&req.method==='GET'){await row(id,who);const r=await reconcile(id);if(r.payment_status!=='paid'||!r.package_path)throw new ServiceError(403,'A paid delivered engagement is required');const blob=await get(r.package_path,{access:'private',token:process.env.UNDERWRITER_BLOB_READ_WRITE_TOKEN});if(!blob?.stream)throw new ServiceError(503,'Delivery temporarily unavailable');res.setHeader('Content-Type','application/zip');res.setHeader('Content-Disposition',`attachment; filename="underwriter-${r.id}.zip"`);res.setHeader('X-Package-SHA256',r.package_sha256);await pipeline(Readable.fromWeb(blob.stream),res);return;}
 throw new ServiceError(404,'Endpoint not found');
 }catch(e){if(res.headersSent){res.end();return;}res.status(e instanceof z.ZodError?400:e.status||503).json({error:e instanceof z.ZodError?'Invalid or incomplete request fields':e instanceof ServiceError?e.message:'Configuration service temporarily unavailable'});}}
