const $=id=>document.getElementById(id);let operator=false,offset=0,busy=false;const message=s=>{$('message').textContent=s;};
async function api(action,method='GET',body,id){const token=await window.Clerk.session?.getToken();const r=await fetch(`/api/configuration/${action}${id?`?id=${encodeURIComponent(id)}`:''}`,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request unavailable');return d;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);message('Working...');try{await fn();message('Request completed.');}catch(e){message(e.message);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function el(tag,text,parent,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;parent?.append(e);return e;}
function button(text,parent,fn){const b=el('button',text,parent,'button');b.type='button';b.onclick=()=>run(fn);return b;}
function field(form,label,name,value='',type='text'){const l=el('label',label,form);const e=el(type==='textarea'?'textarea':'input','',l);e.name=name;e.value=value;if(type!=='textarea')e.type=type;return e;}
function body(form){return Object.fromEntries(new FormData(form));}
async function load(){const d=await api(`list?operator=${operator}&offset=${offset}`);$('operator').hidden=!d.operator;$('operator').textContent=operator?'Customer view':'Operator view';$('inquiry').hidden=operator;$('list-title').textContent=operator?'Operator engagements':'Your engagements';$('engagements').replaceChildren();for(const r of d.engagements)render(r);if(!d.engagements.length)el('p','No engagements on this page.',$('engagements'));}
function render(r){const card=el('article','',$('engagements'),'card');el('h3',r.request.firm,card);el('p',`${r.id} · ${r.stage} · Payment: ${r.paymentStatus}`,card);for(const [label,key] of [['Requested runtime','runtime'],['Runtime details','runtimeDetails'],['Contact','contactEmail'],['Requested scope','scope'],['Acceptance criteria','acceptanceCriteria'],['Constraints','constraints']]){el('strong',label,card);el('p',r.request[key]||'Not supplied',card,'copy');}
 if(r.quote){const q=el('section','',card,'quote');el('h3',`Quote revision ${r.quoteRevision} · ${new Intl.NumberFormat('en-US',{style:'currency',currency:r.quote.currency}).format(r.quote.amountCents/100)}`,q);el('p',`Expires ${new Date(r.quote.expiresAt).toLocaleString()}`,q);for(const k of ['scope','acceptanceCriteria','terms']){el('strong',k==='acceptanceCriteria'?'Acceptance criteria':k,q);el('p',r.quote[k],q,'copy');}if(!operator&&!r.acceptedRevision){const label=el('label','',q),check=el('input','',label);check.type='checkbox';label.append(document.createTextNode('I accept this exact scope, acceptance criteria, terms and quoted amount.'));button('Accept quote and continue to payment',q,async()=>{if(!check.checked)throw new Error('Review and accept the quote first.');const d=await api('checkout','POST',{revision:r.quoteRevision,acceptScope:true},r.id);window.location.assign(d.url);});}else if(!operator&&r.acceptedRevision&&['pending','unpaid'].includes(r.paymentStatus)){button('Resume payment',q,async()=>{const d=await api('checkout','POST',{revision:r.acceptedRevision,acceptScope:true},r.id);window.location.assign(d.url);});}}
 const controls=el('div','',card,'controls');button('Refresh payment status',controls,async()=>{await api('refresh','POST',{},r.id);await load();});
 if(r.packageReady){el('h3','Reviewed package delivered',card);el('p',r.deliveryNote,card,'copy');if(!operator){button('Download private package',controls,async()=>{const token=await window.Clerk.session.getToken();const response=await fetch(`/api/configuration/download?id=${r.id}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const d=await response.json();throw new Error(d.error);}const url=URL.createObjectURL(await response.blob());const link=el('a','',document.body);link.href=url;link.download=`underwriter-${r.id}.zip`;link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);});if(!r.customerAcceptedAt){const label=el('label','',card),check=el('input','',label);check.type='checkbox';label.append(document.createTextNode('I reviewed the delivered work against the agreed acceptance criteria and accept this delivery.'));button('Accept delivery',card,async()=>{if(!check.checked)throw new Error('Review the delivery before accepting.');await api('accept-delivery','POST',{acceptDelivery:true},r.id);await load();});}else el('p',`Delivery accepted ${new Date(r.customerAcceptedAt).toLocaleString()}`,card);}}
 if(operator){const f=el('form','',card);el('h3','Operator handling',f);field(f,'Internal note','note',r.operatorNote,'textarea');const stage=field(f,'Stage: new, reviewing or configuring','stage',['new','reviewing','configuring'].includes(r.stage)?r.stage:'reviewing');button('Save handling note',f,async()=>{await api('note','POST',body(f),r.id);await load();});if(!r.acceptedRevision){const q=el('form','',card);el('h3','Publish an explicit quote',q);el('p','Quote only actual agreed deliverables. Publishing does not send email; the customer sees the quote in their account.',q);field(q,'Amount in USD cents (whole integer)','amountCents',r.quote?.amountCents||'','number');field(q,'Scope','scope',r.quote?.scope||'','textarea');field(q,'Acceptance criteria','acceptanceCriteria',r.quote?.acceptanceCriteria||'','textarea');field(q,'Service terms, delivery expectations and refund policy','terms',r.quote?.terms||'','textarea');field(q,'Expiry','expiresAt','','datetime-local');button('Publish quote for customer review',q,async()=>{const d=body(q);await api('quote','POST',{...d,amountCents:Number(d.amountCents),currency:'usd',revision:r.quoteRevision,expiresAt:new Date(d.expiresAt).toISOString()},r.id);await load();});}}}
$('request-form').onsubmit=e=>{e.preventDefault();run(async()=>{const form=e.target,d=body(form);const request={...d,consent:true};const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(request))))).map(b=>b.toString(16).padStart(2,"0")).join("");let saved;try{saved=JSON.parse(sessionStorage.getItem('uw-inquiry-retry'));}catch{}const id=saved?.fingerprint===fingerprint?saved.id:crypto.randomUUID();sessionStorage.setItem('uw-inquiry-retry',JSON.stringify({id,fingerprint}));await api('inquiry','POST',{...request,id});sessionStorage.removeItem('uw-inquiry-retry');form.reset();await load();});};
$('refresh').onclick=()=>run(load);$('operator').onclick=()=>run(async()=>{operator=!operator;offset=0;await load();});$('previous').onclick=()=>run(async()=>{offset=Math.max(0,offset-50);await load();});$('next').onclick=()=>run(async()=>{offset+=50;await load();});
async function script(src,key){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.crossOrigin='anonymous';if(key)s.setAttribute('data-clerk-publishable-key',key);s.onload=resolve;s.onerror=()=>reject(new Error('Sign-in is unavailable'));document.head.append(s);});}
try{const r=await fetch('/api/configuration/config');const c=await r.json();if(!r.ok||!c.publishableKey)throw new Error(c.error||'Configuration service sign-in is not configured.');const domain=atob(c.publishableKey.split('_')[2]).slice(0,-1);if(!/^[a-zA-Z0-9.-]+$/.test(domain))throw new Error('Invalid sign-in configuration');await script(`https://${domain}/npm/@clerk/clerk-js@5/dist/clerk.browser.js`,c.publishableKey);await window.Clerk.load();if(!window.Clerk.user){message('Sign in to create and track your private configuration engagement.');const login=el('a','Sign in with your Fusion account',$('signin'),'button');login.href='https://fusiondataco.com/sign-in?product=underwriter-configuration';const signup=el('a','Create a Fusion account',$('signin'),'button');signup.href='https://fusiondataco.com/sign-up?product=underwriter-configuration';}else{window.Clerk.mountUserButton($('account'));$('workspace').hidden=false;await load();message('Your configuration workspace is ready.');}}catch(e){message(e.message);}
